import type { Metadata } from "next";
import { PT_Serif } from "next/font/google";
import "./globals.css";

const ptserif = PT_Serif({
  variable: "--font-pt-serif",
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Dynamic Table",
  description: "Generated by Ghourchiani",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ptserif.variable} antialiased bg-gray-100`}>
        {children}
      </body>
    </html>
  );
}
